# Generated by Django 4.1.6 on 2023-02-16 20:52

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'authors'},
        ),
        migrations.AlterModelOptions(
            name='bookauthor',
            options={'verbose_name_plural': 'book authors'},
        ),
        migrations.AlterModelOptions(
            name='bookcatagory',
            options={'verbose_name_plural': 'book catagories'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name_plural': 'publishers'},
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_page',
            field=models.ImageField(upload_to=api.models.bookCoverImagePath),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='ISBN'),
        ),
    ]
