# Generated by Django 4.1.6 on 2023-02-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bookauthor_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='additional_info',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
