# Generated by Django 4.1.6 on 2023-02-17 06:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='cimage',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
