# Generated by Django 4.1.6 on 2023-02-17 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_author_cimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='cimage',
            new_name='image',
        ),
    ]
