# Generated by Django 4.1.6 on 2023-02-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_cimage_author_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_page',
        ),
    ]
